#!/bin/bash

NEED_BINS="pylint pylint3"
SRC_DIR=$(dirname $0)

# Check for needed binaries
for bin in $NEED_BINS; do
    which $bin &>/dev/null || { echo "[ERROR] $bin not found in PATH."; exit 1; }
done

cd $SRC_DIR/../src

echo rsync -lr --exclude `basename $(dirname $0)` ./ ~/
rsync -lr --exclude `basename $(dirname $0)` ./ ~/

echo "Install all Vundle Plugins"
vim +PluginInstall +qall

# Creating needed directories
[[ -d ~/backup/vim || -d ~/tmp ]] || mkdir -p ~/backup/vim


echo "Done"

